spring:
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: src/main/resources/ddl_jpa_creation.sql
  datasource:
    url: 'jdbc:h2:file:/tmp/addressbook'
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  flyway:
    enabled: true
