spring:
  profiles:
    active: dev
  banner:
    location: classpath:banner.txt
server:
  servlet:
    context-path: /addressbook
exception:
  all:
    message: Error processing request
  user:
    exists:
      message: User %s already exists
    not-found:
      message: User %s not found
  addressBook:
    exists:
      message: Address Book with name %s already exists for user %s
    not-found:
      message: Address Book with Id %d not found
  contact:
    exists:
      message: Contact with following details already exists - %s, %s, %s
    not-found:
      message: Contact with Id %d not found
