spring:
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      use-new-id-generator-mappings: false
  datasource:
    url: "jdbc:h2:mem:addressbook"
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  show-sql: true
  flyway:
    enabled: true
logging:
  file: /var/log/addressbook.log
  level:
    root: info
    org:
      springframework:
        web: info
      hibernate: info