spring:
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      use-new-id-generator-mappings: false
      default_schema: "public"
  #    properties:
  #      javax:
  #        persistence:
  #          schema-generation:
  #            create-source: metadata
  #            scripts:
  #              action: create
  #              create-target: src/main/resources/ddl_jpa_creation.sql
  datasource:
    url: 'jdbc:h2:mem:addressbook'
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  flyway:
    enabled: false