ALTER TABLE ADDRESS_BOOKS ADD CONSTRAINT UK_8UMO2VY6OX65YLN40X8S1LQX2 UNIQUE (ADDRESS_BOOK_NAME);
ALTER TABLE CONTACTS ADD CONSTRAINT UK_3SM3VVCGBB4XDHI6NVJMGNHD8 UNIQUE (CONTACT_HASH);
ALTER TABLE USERS ADD CONSTRAINT UK_K8D0F2N7N88W1A16YHUA64ONX UNIQUE (USER_NAME);
ALTER TABLE ADDRESS_BOOKS ADD CONSTRAINT FK2DJ8OHYCF9G1LF18YPKCY8VXW FOREIGN KEY (OWNER_ID) REFERENCES USERS;
ALTER TABLE CONTACTS ADD CONSTRAINT FK53X4IHL1WMIRIUN7WJ3VVLIS0 FOREIGN KEY (ADDRESS_BOOK_ID) REFERENCES ADDRESS_BOOKS;
